estimator:
#  - name: age-extractor
#    params: {}
#  - name: categorical-encoder
#    params: 
#      one_hot: false
#      force_dense_array: true
  - name: standard-scaler
    params: {}
  - name: base-clasificador
    params: {}


data:
  filepath: ./train_classification.csv

metrics:
  - name: precision score
    params: {}

search:
  jobs: -1
  grid:   
    - name: lineal-classifier
      params:
        solver: ["auto", "svd", "cholesky", "lsqr", "sparse_cg", "sag", "saga"]
        alpha : [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
        normalize : [True, False]
        tol : [0.1,0.001,0.01]
        fit_intercept : [True, False]
export:
  output_dir: ./models

reports:
  dir: ./reports