estimator:
#  - name: age-extractor
#    params: {}
#  - name: categorical-encoder
#    params: 
#      one_hot: false
#      force_dense_array: true
  - name: standard-scaler
    params: {}
  - name: Random-forest-classifier
    params: 
      criterion: entropy
      max_depth: 2
      max_features: sqrt
#  - name: Logis-ticRegression
#    params: 
#      solver: "liblinear"
#      random_state: 0


data:
  filepath: ./train_classification.csv

metrics:
  - name: precision score
    params: {}

search:
  jobs: -1
  grid:   
    - name: Random-forest-classifier
      params:
        criterion: ["gini", "entropy"]
        max_depth: [1,2,3,4,5]
        max_features: [1,10,"auto", "sqrt", "log2"]
export:
  output_dir: ./models

reports:
  dir: ./reports