estimator:
#  - name: age-extractor
#    params: {}
#  - name: categorical-encoder
#    params: 
#      one_hot: false
#      force_dense_array: true
  - name: standard-scaler
    params: {}
  - name: Random-forest-classifier
    params: {}

data:
  filepath: ./train_classification.csv

metrics:
  - name: precision score
    params: {}

search:
  jobs: -1
  grid:   
    - name: Random-forest-classifier
      params:
        criterion: ["gini", "entropy"]
        max_depth: [1,5,10,50,70,100,150]
        max_features: [1,10,"auto", "sqrt", "log2"]
export:
  output_dir: ./models

reports:
  dir: ./reports